ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, 16.0
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'GoogleMapsPlusExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end

    # --- SVGKit Patch ---
    require 'fileutils'
    svgkit_path = File.join(installer.sandbox.pod_dir('SVGKit'), 'Source')

    # node fix
    Dir.glob(File.join(svgkit_path, '**', '*.{h,m}')).each do |file|
      FileUtils.chmod("u+w", file)
      text = File.read(file)
      new_contents = text.gsub('#import "Node.h"', '#import "SVGKit/Node.h"')
      File.open(file, 'w') { |f| f.write(new_contents) }
      # puts "Patched Node import in: #{file}"
    end

    # import CSSValue.h
    Dir.glob(File.join(svgkit_path, '**', '*.{h,m}')).each do |file|
      FileUtils.chmod("u+w", file)
      text = File.read(file)
      new_contents = text.gsub('#import "CSSValue.h"', '#import "SVGKit/CSSValue.h"')
      File.open(file, 'w') { |f| f.write(new_contents) }
      # puts "Patched CSSValue import in: #{file}"
    end

    # import SVGLength.h
    Dir.glob(File.join(svgkit_path, '**', '*.{h,m}')).each do |file|
      FileUtils.chmod("u+w", file)
      text = File.read(file)
      new_contents = text.gsub('#import "SVGLength.h"', '#import "SVGKit/SVGLength.h"')
      File.open(file, 'w') { |f| f.write(new_contents) }
      # puts "Patched SVGLength import in: #{file}"
    end
  end
end
