import {
  type ConfigPlugin,
  withAppDelegate,
  withInfoPlist,
  withPodfile,
  withPodfileProperties,
} from '@expo/config-plugins';
import {
  mergeContents,
  removeContents,
} from '@expo/config-plugins/build/utils/generateCode';

import type { RNGoogleMapsPlusExpoPluginProps } from '../types';

const withIosGoogleMapsPlus: ConfigPlugin<RNGoogleMapsPlusExpoPluginProps> = (
  config,
  props
) => {
  config = withInfoPlist(config, (conf) => {
    const apiKey =
      props?.googleMapsIosApiKey ?? process.env.GOOGLE_MAPS_API_KEY_IOS ?? null;

    if (!apiKey) {
      console.warn(
        '[react-native-google-maps-plus] No iOS API key provided. Google Maps may fail to initialize.'
      );
    }
    if (apiKey) {
      conf.modResults.MAPS_API_KEY = apiKey;
    }
    return conf;
  });

  config = withPodfileProperties(config, (conf) => {
    // The native dependencies are Swift packages, so the pods have to be
    // installed as frameworks. React Native recommends dynamic linking for
    // Swift packages, static linking may cause linker errors. An explicit
    // choice made by the app (e.g. via expo-build-properties) is kept.
    if (!conf.modResults['ios.useFrameworks']) {
      conf.modResults['ios.useFrameworks'] = 'dynamic';
    }
    return conf;
  });

  config = withPodfile(config, (conf) => {
    // The svgkit patch script no longer ships with the package, so a block
    // generated by a previous plugin version has to be removed, `pod install`
    // would fail on the missing require otherwise.
    let src = removeContents({
      src: conf.modResults.contents,
      tag: 'react-native-google-maps-svgkit-patch',
    }).contents;

    if (!src.includes('use_modular_headers!')) {
      src = mergeContents({
        tag: 'react-native-google-maps-modular-headers',
        src,
        newSrc: 'use_modular_headers!',
        anchor: /use_frameworks!|platform\s+:ios.*/,
        offset: 1,
        comment: '#',
      }).contents;
    }

    conf.modResults.contents = src;
    return conf;
  });

  config = withAppDelegate(config, (conf) => {
    const { language } = conf.modResults;
    if (language !== 'swift') {
      console.warn(
        '[react-native-google-maps-plus] AppDelegate is not Swift; skipping GMSServices injection.'
      );
      return conf;
    }

    let src = conf.modResults.contents;

    if (!src.includes('import GoogleMaps')) {
      src = mergeContents({
        tag: 'react-native-google-maps-import',
        src,
        newSrc: 'import GoogleMaps',
        anchor: /^import React/m,
        offset: 1,
        comment: '//',
      }).contents;
    }

    const initSnippet = `
    if let apiKey = Bundle.main.object(forInfoDictionaryKey: "MAPS_API_KEY") as? String {
      GMSServices.provideAPIKey(apiKey)
    }`;

    try {
      src = mergeContents({
        tag: 'react-native-google-maps-init',
        src,
        newSrc: initSnippet,
        anchor:
          /return\s+super\.application\s*\(\s*application\s*,\s*didFinishLaunchingWithOptions:\s*launchOptions\s*\)/,
        offset: -1,
        comment: '//',
      }).contents;
    } catch (error: any) {
      if (error.code === 'ERR_NO_MATCH') {
        src = mergeContents({
          tag: 'react-native-google-maps-init',
          src,
          newSrc: initSnippet,
          anchor: /didFinishLaunchingWithOptions[^{]*\{/,
          offset: 1,
          comment: '//',
        }).contents;
      } else {
        throw error;
      }
    }

    conf.modResults.contents = src;
    return conf;
  });

  return config;
};

export default withIosGoogleMapsPlus;
