disabled_rules:
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - closure_parameter_position
  - todo

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 100

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

reporter: 'xcode'
