name: Release Package
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn build

  release:
    runs-on: ubuntu-latest
    needs: [build-library]
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          ref: main
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build tarball
        run: |
          mkdir -p release
          npm pack --pack-destination release

      - name: Debug OIDC Token length
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=npm" | jq -r '.value')
          echo "OIDC token length: ${#TOKEN}"


      - name: Check semantic-release/npm version
        run: yarn why @semantic-release/npm

      - name: Check semantic-release version
        run: yarn why semantic-release

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
