name: Release Package
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          ref: main
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn build

      - name: Build tarball
        run: |
          mkdir -p release
          npm pack --pack-destination release

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# TODO: remove NPM_TOKEN
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
