name: Close Stale Issues
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          exempt-issue-labels: 'pinned,important'
          days-before-issue-stale: 7
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          stale-issue-message: 'No activity for 7 days. Marking as stale.'
          close-issue-message: 'Closed automatically due to inactivity.'
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
